name: Release ExampleMod
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: zulu
          java-version: 17

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew build

      - name: Read Properties
        id: 'properties'
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: 'mod_id mod_name'

      - name: Get Version
        id: var
        run: |
          MESSAGE=$(ls build/libs/* | grep sources.jar -v | grep shadow.jar -v | grep slim.jar -v | awk -F '${{ steps.properties.outputs.mod_id }}-|.jar' '{print $2}')
          echo version=$MESSAGE >> $GITHUB_OUTPUT
      
      - name: "publish md mod"
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          name: "${{ steps.properties.outputs.mod_name }} v${{ steps.var.outputs.version }}"
          version: ${{ steps.var.outputs.version }}
          game-versions: 1.20.1
          version-type: release
          java: 17
          loaders: forge

          github-token: ${{ secrets.GITHUB_TOKEN }}

          modrinth-id: AABBCCDD
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 114514
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
